name: linter


on:
   pull_request:
   push:
     branches:
       - main
   workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
