name: linter


on:
   pull_request:
   push:
     branches:
       - main
   workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hadolint Dockerfile Analysis
        uses: hadolint/hadolint-action@v1.5.0
        with:
            dockerfile: Dockerfile
